spring:
  config:
    import: optional:file:.env[.yml]
  application:
    name: menu-admin
  datasource:
    url: jdbc:mariadb://localhost:3306/menu
    username: eater
    password: ${DB_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      jdbc:
        time_zone: Asia/Seoul
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
  batch:
    job:
      enabled: false
  main:
    allow-bean-definition-overriding: true

server:
  port: 17080

crontab:
#  getMenu: 0 */10 9-11 * * ?
  getMenu: 0 */1 * * * ?